softdevteam/alloy

- src/liballoc/boehm.rs
- src/liballoc/lib.rs
- src/liballoc/vec.rs
- src/libcore/gc.rs
- src/libcore/lib.rs
- src/librustc_hir/lang_items.rs
- src/librustc_mir/transform/mod.rs
- src/librustc_mir/transform/preallocate_gc_contents.rs
- src/libstd/alloc.rs
- src/libstd/build.rs
- src/libstd/gc.rs
- src/libstd/lib.rs
A common GC pattern is to pass a `Vec<T>` to a `Gc` to be managed by the collector. This requires the collector to register a finalizer in order to call `Vec`'s drop method - even if `needs_drop::<T>() == false`! This PR seeks to fix that by allowing the compiler to ignore `Vec<T>::drop` (and hence, remove the need to register a finalizer) if it is safe to do so.
To summarise how this works, this PR  does three things:
- A new trait `ManageableContents` is introduced in `libcore`, this is to be implemented on every `T` whose contents are safe to be allocated with Boehm and not be dropped. The name is utterly rubbish, and a placeholder for now -- feel free to come up with suggestions (I'd like it to be relatively terse).
- Stubs for the Boehm allocator are added to `liballoc` to allow the …
> Patch Vec constructors to alloc with Boehm

- src/liballoc/gc.rs
- src/liballoc/lib.rs
- src/libcore/gc.rs
- src/libstd/gc.rs
- src/libstd/lib.rs
This one should be fairly straightforward to review as most of the code from `liballoc/gc.rs` is lifted straight from rboehm. 
Since all GC related work is now gated behind a consistent unstable GC feature, the user will need add `#![feature(gc)]` to use the `Gc` type in their code.
> Add API for Gc smart pointer

- src/liballoc/gc.rs
- src/liballoc/lib.rs
- src/libcore/gc.rs
- src/libstd/gc.rs
This is the missing piece of the puzzle in order for `Gc<Vec<T>>` to optimise away finalizers on Gc values where `T: ManageableContents`. 
Up until this PR, `Vec`s could be pre-emptively allocated in a Gc region, but were still having finalizers registered anyway. Which caused some head-scratching as I wondered why this had 0 impact on wall-clock time when running a synthetic benchmark - oops!
> Prevent registering of unnecessary finalizers for `Gc<Vec<T>>`

- src/liballoc/gc.rs
- src/librustc_mir/transform/preallocate_gc_contents.rs
- src/librustc_session/options.rs
This PR introduces support for optimising away finalizers for Vecs whose element
types can be statically determined not to need dropping.
This requires the user to specify `Boehm` as the global allocator in their
crate, and the -Zgc-destination-propagation flag must be enabled.
Right now, this won't work recursively. In other words, if one were to create a
value with the following type:
Gc<Vec<Vec<usize>>
A finalizer would still be registered unnecessarily.
This is because the MIR pass which determines which Vecs are allocated directly
in GC space currently looks only at the top-level element type inside a Vec.
Gc<Vec<Vec<usize>>
^   ^
|   |
|   +---- No Finalizer
+----- Finalizer
In order for both finalizers to be removed, one must implement
`ManageableContents` for `Vec<usize>`.
> Automatically determine when finalizers can be omitted

- compiler/rustc_codegen_llvm/src/intrinsic.rs
- compiler/rustc_hir/src/lang_items.rs
- compiler/rustc_middle/src/query/mod.rs
- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir/src/interpret/intrinsics.rs
- compiler/rustc_span/src/symbol.rs
- compiler/rustc_ty/src/common_traits.rs
- compiler/rustc_ty/src/needs_drop.rs
- compiler/rustc_typeck/src/check/intrinsic.rs
- library/core/src/gc.rs
- library/core/src/intrinsics.rs
- library/core/src/lib.rs
- library/core/src/mem/mod.rs
- src/librustc_hir/lang_items.rs
- src/test/ui/consts/const-needs_finalize.rs
Finalization can be very expensive, and when a `Gc` manages the memory for a particular type, it's not always obvious if a finalizer is required. Up until now, the collector will err on the side of caution: if unsure, it will register finalizers for types even when this may not be strictly necessary. 
To try and win back some of the performance we lose by being overly liberal with finalization, this PR provides an API for the user to tell the GC that values of a certain type don't need finalizing. It comes in two parts:
1. A `NoFinalize` marker trait which can be implemented on types where the user is sure finalization isn't necessary
2. A `needs_finalizer::<T>()` intrinsic, which, like `needs_drop`, will return `true` if `Gc<T>` should register a finalizer. This is semantically identical …
> Pave the way for users to opt-out of finalization

- library/alloc/src/boehm.rs
- library/boehm_shim/src/lib.rs
This makes the API compatible with https://github.com/softdevteam/rboehm/pull/25
> Allow boehm::register_finalizer to take a null fn pointer

- library/alloc/src/boehm.rs
At first this seems counter-intuitive: why put memory that should be
managed with RAII under control of the collector? However, this is
necessary to prevent leaks if we want to take advantage of `NoFinalize`
optimisations. This is best explained with an example:
let bigvec: Vec<usize> = ...;
let gc = Gc::new(bigvec);
Here, `bigvec` has a `drop` method which does the following: recursively
call drop on each element; then, deallocate the memory for the backing store
(`RawVec`). When `bigvec` is moved into `Gc`, its `drop` method is
converted from a destructor to a finalizer, and may run later on when
Boehm determines that it's no longer reachable. Unfortunately, this kind
of finalization is very expensive, and leads to bottlenecks in the
collector which can make it impractical to use.
The …
> Replace gc_malloc_uncollectable with gc_malloc for non-GC'd values

- library/alloc/src/string.rs
- src/test/ui/consts/const-needs_finalize.rs
A String in Rust is implemented as a `Vec<u8>`. This doesn't need
finalizing when used in a Gc. Marking it with `NoFinalize` will ensure
that `mem::needs_finalizer::<String>()` returns `false`.
> Mark Strings as NoFinalize

- library/core/src/gc.rs
- src/test/ui/layout/gc-layout.rs
The major changes here are the API change in `gc_layout::<T>` to now return a `Trace` struct, and the addition of the `Conservative` trait.
> Various small changes in core::gc

- Cargo.lock
- library/alloc/Cargo.toml
- library/alloc/src/lib.rs
- library/std/Cargo.toml
- src/tools/tidy/src/deps.rs
- src/tools/tidy/src/extdeps.rs
This is difficult one to raise, because the libgc_internal work was quite a lot of work to implement. However, it's a sunk cost. In doing the work for https://github.com/softdevteam/rustgc/pull/23, I worked out that rustgc doesn't actually need to know the exact implementation details of the Allocator API. This greatly simplifies things, as we won't need to maintain 3 separate repositories and worry about raising PRs in the correct order.
> Revert libgc_internal crate

- src/test/codegen/alloc-optimisation.rs
- src/test/codegen/vec-optimizes-away.rs
This also lets us re-enable the tests.
> Bump LLVM after alloc optimisation fix

- library/alloc/Cargo.toml
- library/alloc/src/lib.rs
- library/std/Cargo.toml
- library/std/src/alloc.rs
- src/tools/tidy/src/deps.rs
- src/tools/tidy/src/extdeps.rs
Once https://github.com/softdevteam/libgc/pull/51 lands, this can be merged.
> Include libgc's allocator as part of standard library

- compiler/rustc_hir/src/lang_items.rs
- compiler/rustc_middle/src/query/mod.rs
- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir/src/transform/mod.rs
- compiler/rustc_mir/src/transform/prevent_early_finalization.rs
- compiler/rustc_span/src/symbol.rs
- compiler/rustc_ty_utils/src/common_traits.rs
- library/core/src/gc.rs
- src/test/mir-opt/prevent_early_finalization.preserve_args.PreventEarlyFinalization.diff
- src/test/mir-opt/prevent_early_finalization.preserve_args_inl.Inline.after.mir
- src/test/mir-opt/prevent_early_finalization.preserve_args_inner.PreventEarlyFinalization.diff
- src/test/mir-opt/prevent_early_finalization.preserve_locals.PreventEarlyFinalization.diff
- src/test/mir-opt/prevent_early_finalization.preserve_multiple_locals.PreventEarlyFinalization.diff
- src/test/mir-opt/prevent_early_finalization.rs
This is a draft PR because I'm still debugging the test suite.
Currently `Gc` is defined in the libgc crate. The compiler isn't aware
of this so can't perform any specific operations on the `Gc` type. To
fix this, we introduce a `GcSmartPointer` trait which `libgc::Gc` will
implement.
This should be temporary. Eventually, the `Gc` smart pointer will be
part of the standard library. Right now though, it's convenient for
development that they are separated.
> Prevent early finalization

- compiler/rustc_codegen_cranelift/example/mini_core.rs
- compiler/rustc_ty_utils/src/needs_drop.rs
- library/alloc/src/boxed.rs
- library/alloc/src/raw_vec.rs
- library/alloc/src/vec/mod.rs
- library/core/src/gc.rs
- library/core/src/tuple.rs
- src/test/ui/gc/needs_finalize.rs
Previously `std::mem::needs_finalize<T>()` would only return `true` if
the top-level type required finalizing. This now traverses component
types correctly. See `test/ui/gc/needs_finalize.rs` for a detailed list
of which types need finalizing.
A lot of the refactoring in `needs_drop` comes from breaking changes in
upstream.
> Fix broken behaviour for NoFinalize trait

- library/alloc/src/boxed.rs
- library/alloc/src/raw_vec.rs
- library/alloc/src/string.rs
- library/alloc/src/vec/mod.rs
- library/core/src/gc.rs
- library/core/src/tuple.rs
- src/test/ui/gc/needs_finalize.rs
The `NoFinalize` trait prevents a type `T` from being finalized when its
passed to `Gc<T>`.
Now that we've settled on a preferred semantics for `NoFinalize`, the implementation here was already correct. I've tweaked it to be unsafe, added a couple more tests, and documented it.
> Mark `NoFinalize` as unsafe and document it.

- .buildbot_dockerfile_debian
rustgc is now CI'd on a minimal docker container on the soft-dev build server. We need to explicitly install the rustc dependencies for each build.
> Add rustc dependencies for containerised CI

- library/boehm/build.rs
The softdev fork of the BDWGC allows for dynamic switching between collectable and non-collectable GC allocations, which means we can take advantage of the `NoFinalize` trait to optimise away unnecessary finalizers.
> Switch to custom BDWGC fork

- Cargo.lock
- library/boehm/Cargo.toml
- library/boehm/build.rs
- library/boehm/src/boehm.rs
- library/boehm/src/lib.rs
- library/std/src/rt.rs
Rust's build system has better support for cmake than autotools. I'm also more familiar with cmake and I find it easier to quickly switch build options when developing.
> Switch to building Boehm with cmake

- Cargo.lock
- compiler/rustc_codegen_llvm/src/intrinsic.rs
- compiler/rustc_metadata/Cargo.toml
- compiler/rustc_metadata/src/rmeta/encoder.rs
- compiler/rustc_monomorphize/src/collectable_trait.rs
- compiler/rustc_monomorphize/src/collector.rs
- compiler/rustc_monomorphize/src/lib.rs
- src/test/codegen-units/item-collection/auxiliary/cgu_export_collect_trait_impl.rs
- src/test/codegen-units/item-collection/make-collectable-intrinsic.rs
After MIR lowering, rustc runs a "monomorphization collector" which determines which monomorphized function symbols should be available during the codegen phase. This can be thought of as a kind of tree shaker which walks the CFG from a predetermined set of roots looking for all instances of function calls. Those which are found are added to a "mono-list".
The purpose of `std::mem::make_collectable<T>(value: &T)` is to recurse through the fields of `value` and call `Collectable::set_collectable` on all fields whose type implements `Collectable`. However, since the body for this intrinsic is generated during codegen -- which is after the mono collector has already run -- rustc won't know that calls to `set_collectable` need to be kept in the binary.
This commit therefore patches the mono …
> Ensure `Collectable` trait method symbols are linked

- compiler/rustc_codegen_llvm/src/intrinsic.rs
- compiler/rustc_codegen_llvm/src/intrinsic_util.rs
- compiler/rustc_codegen_llvm/src/lib.rs
- compiler/rustc_monomorphize/src/collectable_trait.rs
- compiler/rustc_typeck/src/check/intrinsic.rs
- library/core/src/mem/mod.rs
- src/test/ui/gc/make_collectable.rs
This is used to dynamically switch an allocated value from non-collectable to collectable. It works by recursing through the typeof a value and generating calls to `Collectable::set_collectable` for all component types which implement the `Collectable` trait.
Not all type kinds are implemented, and will cause an ICE if `make_collectable` is passed a value of an unimplemented type.
> Add `make_collectable` intrinsic

- compiler/rustc_hir/src/lang_items.rs
- compiler/rustc_middle/src/query/mod.rs
- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_span/src/symbol.rs
- compiler/rustc_ty_utils/src/common_traits.rs
- compiler/rustc_ty_utils/src/needs_finalizer.rs
- library/alloc/src/boxed.rs
- library/alloc/src/raw_vec.rs
- library/alloc/src/vec/mod.rs
- library/core/src/cell.rs
- library/core/src/gc.rs
- library/core/src/option.rs
- library/core/src/ptr/unique.rs
- src/test/ui/gc/needs_finalize.rs
Collection types such as Vec<T> have drop methods which are
only necessary if T requires dropping. This can be managed partially by
implementing `NoFinalize` on `Vec<T>`:
unsafe impl<T: NoFinalize> NoFinalize for Vec<T> {}
However, this will return true for needs_finalize if `T: !Drop` but also
doesn't implement `NoFinalize`.
To get around this, we introduce a trait which is expected only to be
used in the standard library called `OnlyFinalizeComponents`.
Implementing this trait on a type indicates to the collector that it can
ignore that type's drop method, but it must still recurse through the
type's components to see if any of them need dropping.
> Prevent collections from unnecessarily finalizing elems

- library/alloc/src/gc.rs
- src/test/ui/gc/needs_finalize.rs
The liveness of each Gc value is calculated independently by the
collector, so it's never necessary to call the drop method of a Gc from
another Gc's finalizer.
> Make Gc<T> implement NoFinalize

- compiler/rustc_hir/src/lang_items.rs
- compiler/rustc_monomorphize/src/collector.rs
- compiler/rustc_span/src/symbol.rs
- library/core/src/intrinsics.rs
- library/core/src/mem/mod.rs
Intrinsics can't be lang_items so to get around this we hid it behind a
no-inline core library function of the same name so that it appeared in
the monomorphisation collector.
By switching to using a rustc_diagnostic_item, we don't need to use a
lang_item anymore and we can match on the intrinsic directly. This also
means that the first `make_collectable` call can be inlined away.
> Allow make_collectable to be inlined

- compiler/rustc_mir_transform/src/lib.rs
- compiler/rustc_mir_transform/src/prevent_early_finalization.rs
- library/core/src/intrinsics.rs
This relied on patching an llvm_asm statement to the end of a MIR block.
llvm_asm is now deprecated, so instead we patch a call to the black_box
intrinsic, which does the same thing.
> Fix prevent_early_finalization pass

- library/alloc/src/gc.rs
The introduction of new allocation methods from dynamic allocation
switching support in Boehm seems to have caused `allocate_untraceable`
to be sometimes erroneously be used on blocks which contain pointers.
We should fall back to allocating blocks conservatively while I
investigate it.
> Disable atomic allocation

- library/alloc/src/gc.rs
`Send` is only required for certain impl blocks that have constructors.
> Remove unnecessary `Send` bound for trait impls

- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_mir_transform/src/lib.rs
- compiler/rustc_span/src/symbol.rs
- library/alloc/src/gc.rs
- src/test/ui/gc/check_finalizers.rs
- src/test/ui/gc/check_finalizers.stderr
The GC runs finalizers on a separate thread, which means that values with drop implementations must be `Send` + `Sync`. This puts a big restriction on which types can be passed to `Gc::new`.
There are cases where Gc does not need to run finalizers for a value because a) it doesn't have a drop method, or b) the drop call is removed by finalizer optimisation. However, these values are still prevented from being passed to Gc new because there's no way to check that `T: Send + Sync + !Drop` in the type system.
This pass allows such values to be constructed with `Gc::new` by removing the `T: Send + Sync` bound on `Gc::new`, but then uses a MIR pass later in the pipeline to check that if those values require dropping, they implement `Send + Sync`.
We could allow more legal types to pass this …
> Add MIR pass to verify finalizers can be run safely

- library/alloc/src/gc.rs
This better matches `Rc::as_ptr` and friends. Practically speaking, it doesn't make much difference to `Gc` since `Gc` is `Copy`, but using `as_ptr(&Self)` forces callers to add a `&` reference which then makes converting `Gc::as_ptr` to `Rc::as_ptr` easier.
> `as_ptr` typically takes `&Self`.

- compiler/rustc_span/src/symbol.rs
- compiler/rustc_ty_utils/src/needs_finalizer.rs
- library/core/src/gc.rs
- src/test/ui/gc/needs_finalize.rs
Sometimes it's necessary to prevent finalization on a per-use basis. This can happen when it's not possible to implement `FinalizerOptional` on types because were defined outside of the current crate (due to the orphan rule).
This updates the `NonFinalizable` container to respect the new semantics and adds some tests for it.
> Update `NonFinalizable` container

- library/alloc/src/gc.rs
This is not needed to prevent Drop from happening unless finalized. ManuallyDrop semantics are tricky so removing it makes this less error-prone.
> Remove ManuallyDrop wrapper in GcBox

- compiler/rustc_mir_transform/src/lib.rs
- src/test/codegen/gc.rs
If they linger, they start to interfere with control flow optimisations which assume they don't exist (because `Gc` is copyable).
> Remove GC barriers earlier in LLVM pipeline

- benchmark.config.toml
Most of these options are the default when building rustc with stage 2. It's useful have an explicit config for them so that nothing changes while we are conducting experiments.
> Add config for benchmarking programs with Alloy

- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_span/src/symbol.rs
- library/alloc/src/gc.rs
- library/core/src/gc.rs
- src/test/rustdoc/empty-section.rs
- src/test/rustdoc/issue-50159.rs
- src/test/rustdoc/synthetic_auto/basic.rs
- src/test/ui/gc/check_finalizers.rs
- src/test/ui/gc/check_finalizers.stderr
A potential soundness hole exists in GC finalisers when `Gc<T>`s that contain ordinary Rust references (`&`/`&mut`) are used with finalisers.
Consider the following:
```rust
fn main() {
let b = Box::new(123);
let gc: Gc<&usize> = Gc::new(b.as_ref());
// foo(b);
// dbg(gc); // ERROR: use-after-move
}
```
This kind of program might seem weird, but it is perfectly safe. The lifetime of `gc` is tied to `b`. The compiler catches uses of `gc` after a move of `b` as we'd expect.
If we introduce finalisers into the mix, this can become unsound. It seems like ownership should save us here, after all, `gc` cannot outlive `b`. However, finalisers provide a stealthy way to violate soundness because they can run at the collector's leisure - potentially long after `b` has been dropped. Let's extend the …
> Fix soundness hole in GC finalisers

- .buildbot.config.toml
- .buildbot.sh
- compiler/rustc_ty_utils/src/needs_drop.rs
- tests/ui/runtime/gc/finalizer_elision_cyclic_types.rs
Unlike `needs_drop`, `needs_finalize` must check an ADT's type parameters to be certain it doesn't need finalizing. This has to potential to induce an endless endless cycle during type checking.
This commit refactors the `needs_finalize` implementation to use a cache of previously seen types so that it can ignore them when looking through type parameters, preventing cycles.
> Fix finaliser prevention to correctly deal with type params

- compiler/rustc_mir_transform/src/lib.rs
- tests/ui/runtime/gc/early_finalization.rs
The CriticalCallEdges requries that the CFG has been simplified to its final stage so removing terminators afterwards breaks the LLVM IR.
> Remove gc drops before adding call guard edges

- library/core/src/gc.rs
- tests/ui/runtime/gc/check_finalizers.rs
- tests/ui/runtime/gc/unchecked_finalizer.rs
This can be very useful when using types from third party crates which do not implement `FinalizerSafe`. Instead of implementing `FinalizerSafe` on any `T` with a `!FinalizerSafe` field, we can now ensure each problematic field uses the `FinalizeUnchecked<U>` wrapper. This is safer than a blanket implementation.
> Add wrapper type for opting out of FSA

- library/alloc/src/vec/mod.rs
- tests/ui/runtime/gc/zero_vecs.rs
Since Alloy is a conservative GC, this prevents memory leaks kept alive by stale vector elements.
> Zero vector contents after popping

- README.md
This is just a start, it contains the basic build steps and a (hopefully) motivating example. This still needs to explain the intricacies of finalisers.
> Flesh out a basic README for Alloy

- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_span/src/symbol.rs
- library/core/src/gc.rs
- tests/ui/runtime/gc/check_finalizers.rs
- tests/ui/runtime/gc/check_finalizers.stderr
Previously FSA only checked that drop methods dereferenced `FinalizerSafe` fields. The benefit of this is that it allows a greater number of finalisers to pass because `FinalizerSafe` is concerned with type safety in the context of GC only.
However, as an auto trait, `FinalizerSafe` is automatically implemented on types in third party crates which have no knowledge of Alloy. This could mean that non-Send + non-Sync types are erroneously marked as safe to finalise. In the interest of soundness, we err on the side of caution and modify FSA to check for the existence of `FinalizerSafe + Send + Sync`.
> Change FSA to check for `Send + Sync` explicitly

- library/boehm/build.rs
If you build Alloy with debuginfo in order to debug the compiler, this will build the BDWGC runtime in debug mode too. As the BDWGC is linked into target programs, it will end up using a debug build regardless of the user's cargo flags, this is rarely what we want.
> Always build Boehm in release mode

- library/core/src/gc.rs
This wrapper struct has no runtime semantics (it exists only for a type to opt out of FSA) so there is no need to restrict access to its contents.
> Make `FinalizerUnchecked` inner field public

- library/std/src/rt.rs
If something goes wrong during a GC, we likely want to know what happened.
It's not totally clear whether this is the correct way to disable warnings anyway (it uses some deprecated library features in Boehm). Annoying warnings (such as those for many large page allocations) can be disabled individually.
> Do not suppress all Boehm warnings

- library/alloc/src/gc.rs
- library/alloc/tests/gc.rs
- library/alloc/tests/lib.rs
- library/boehm/src/lib.rs
When a layout's alignment is larger than its size, we must allocate using Boehm's `memalign` function instead of `malloc` in order to mirror the existing behaviour in rustc.
This is checked in rustc with various assertions on pointer read and write intrinsics, and was discovered when they failed with large alloctions in lrlex using a debug build of alloy.
> Use GC_memalign for larger allocations

- Cargo.lock
- library/alloc/src/gc.rs
- library/boehm/Cargo.toml
- library/boehm/src/lib.rs
- library/std/src/sys/unix/thread.rs
- library/std/src/thread/mod.rs
This prevents us from having to register threads explicitly, and can remove a potential source of errors where we supply an incorrect stack bottom.
This is required for https://github.com/softdevteam/alloy/pull/102 to land.
> Switch to using Boehm's pthread drop-in library

- library/boehm/src/lib.rs
- library/std/src/sys/common/thread_local/mod.rs
- library/std/src/sys/common/thread_local/os_local.rs
- library/std/src/sys/unix/thread_local_dtor.rs
- src/bootstrap/test.rs
- tests/codegen/thread-local.rs
- tests/ui/runtime/gc/run_finalizers.rs
- tests/ui/runtime/gc/thread_local.rs
- tests/ui/runtime/gc/unchecked_finalizer.rs
- tests/ui/threads-sendsync/issue-43733-2.rs
- tests/ui/threads-sendsync/issue-43733.rs
In order to support this this PR is split into two commits: 
1. We must disable compiler-based thread local implementation. This is a shame because it's faster than the POSIX thread library impl but it places thread locals in a table in a segment in the binary which Boehm can't scan. It might be possible to fix this in the future, but for now we fallback to using the POSIX thread implementation because there exists a fix for this.
2. We introduce a thread-local rootset vector, which holds pointers to the current thread's TL values. This rootset is then specifically added to Boehm's mark list so that TL values can be traced.
> Allow Boehm to mark from thread-locals

- library/std/src/gc.rs
- library/std/src/rt.rs
- library/std/src/thread/mod.rs
- tests/ui/runtime/gc/run_finalizers.rs
- tests/ui/runtime/gc/unchecked_finalizer.rs
- tests/ui/runtime/gc/zero_vecs.rs
This prevents deadlocks in user code which acquire locks in drop methods. The new approach to finalisation works as follows:
1. During the entry_point, a finalisation thread, and an mpsc channel are initialised.
2. New threads (including the main thread) are given thread local storage (TLS) containing a sender, which is used to pass finalisers to the finalisation thread. This does not require synchronisation.
3. At the end of the GC pause, Boehm will run finalisers for objects which were not marked. This does not run the drop method for the object directly. Instead, it sends the drop method to the finalisation thread to be run later.
4. The finalisation thread iterates through the message queue, calling the finaliser callback for each unreachable object. This finaliser callback amounts to …
> Finalise `Gc<T>` objects on a separate thread

- library/bdwgc/build.rs
This is useful for debugging, where profilers intercept and override dynamically linked symbols (e.g. `malloc` and `free`).
As of this commit, there is no way to build a custom BDWGC fork and have that dynamically link to a program compiled with Alloy automatically. This is because `cargo` does not support bubbling up linker args to the final linked binary, so there is no way to programmatically set the rpath for BDWGC to the OUT directory in `library/bdwgc` [1].
Alloy programs must therefore set the `LD_PRELOAD` environment variable to prevent it from linking against the system libgc.
[1]: https://github.com/rust-lang/cargo/issues/9554
> Allow BDWGC to be linked dynamically

- library/bdwgc/build.rs
- library/bdwgc/src/lib.rs
- library/std/src/gc.rs
This PR updates Alloy to use the `GC_finalize` API implemented in the recent changes to BDWGC (https://github.com/softdevteam/bdwgc/pull/22). It also contains some general tidying up commits.
I measured the performance of these changes on yksom to see if we can get a better idea of the cost of using condition variables in the finaliser thread. The results are shown below.
> Use the `GC_finalize` API for `Gc<T>` types

- library/bdwgc/src/lib.rs
- library/std/src/gc.rs
This is useful for advanced users, who may allow references to GC objects to escape from their Gc<T> smart pointers. In such cases, one must be careful to ensure that a finalizer is not run early because of compiler optimisations (e.g. scalar replacement). This commit provides a unified way to do this using the same mechanism as Gc::drop.
> Add a function for users to keep pointers alive

- library/core/src/gc.rs
Having this field public allowed users to create `FinalizeUnchecked` structs without using the unsafe `new` constructor. This means that users can bypass FSA in safe Rust.
> Remove pub from FinalizeUnchecked field

- compiler/rustc_mir_transform/src/check_finalizers.rs
- tests/ui/runtime/gc/check_finalizers.rs
- tests/ui/runtime/gc/check_finalizers.stderr
This PR creates a single enum to represent the various kinds of FSA errors that Rust programs may exhibit. This is a mostly refactoring commit which hopes to simplify some more complex analysis that we want to perform.
However, this does have one observable impact on the current state of FSA in Alloy: we now emit different errors for types which are `!Send` + `!Sync`, and those which are `!FinalizerSafe`.
On its own, this may seem extraneous, as it now means that types which are `!Send + !Sync + !FinalizerSafe` will now generate two errors instead of one. However, this vastly simplifies future changes to the FSA algorithm, and makes it much easier to 'bail-out' of FSA early when we find bad cases which would not maek sense to recurse further into (e.g. standard library types).
> Refactor FSA error generation

- compiler/rustc_mir_transform/src/check_finalizers.rs
- tests/ui/static/gc/fsa/stdlib_errors.rs
- tests/ui/static/gc/fsa/stdlib_errors.stderr
This does not weaken FSA -- the drop methods of standard library types are still scanned line-by-line. However, if a standard library type contains a drop method with an unsafe projection, a single generic error for that type will be emitted (as opposed to errors on a per-line basis as with user crates).
> Less granular FSA errors for standard library types

- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_span/src/symbol.rs
- library/core/src/gc.rs
- library/core/src/marker.rs
- library/std/src/gc.rs
- tests/rustdoc/auto-trait-bounds-by-associated-type-50159.rs
- tests/rustdoc/empty-section.rs
- tests/rustdoc/synthetic_auto/basic.rs
- tests/rustdoc/synthetic_auto/manual.rs
- tests/ui/runtime/gc/check_finalizers.rs
- tests/ui/runtime/gc/check_finalizers.stderr
- tests/ui/static/gc/fsa/auxiliary/types.rs
- tests/ui/static/gc/fsa/references.rs
- tests/ui/static/gc/fsa/references.stderr
- tests/ui/static/gc/fsa/references_nested.rs
- tests/ui/static/gc/fsa/references_nested.stderr
- tests/ui/static/gc/fsa/stdlib_errors.stderr
Previously FSA prevented `Gc<T>`s from having a finalizer if `T` (directly or indirectly) contained a reference. This made retro-fitting GC to large libraries difficult. It also, somewhat surprisingly, completely prevents finalizable nested `Gc<dyn Trait>`s (due to the underlying vptr being a `&'static` reference).
This commit loosens this restriction, allowing FSA to interrogate drop method bodies (much the same as for `Send + Sync + FinalizerSafe`) looking for unsound uses of references.
This change is based on the following observation: a reference inside of `T`'s drop method is safe to dereference provided it never originates from `T` or one of `T`'s fields. For example:
```rust
fn drop(&mut self) {
let a = 123;
let r1 = &1; // const with 'static lifetime
let r2 = &a; // stack-local …
```
> Allow types containing references to have finalizers

- library/std/src/gc.rs
- library/std/src/gc/tests.rs
As before, this emulates the Rc/Arc API but with support for FSA.
> Add `Gc::from` API for unsized slices

- compiler/rustc_middle/src/query/mod.rs
- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_ty_utils/src/common_traits.rs
Trait resolution (and monomorphization, which can be thought of as a variant of this) is used throughout the FSA algorithm (e.g. checking if `T` implements `Send` / `Sync`, resolving calls to trait methods to their concrete implementation, etc). Unfortunately this can be slow, particularly during a MIR pass, where functions must be monomorphized on demand. This slowdown becomes particularly apparent when trying to extend FSA to look into other function calls which are reachable via drop. On large codebases like rustc (e.g. when bootstrapping) or Alacritty, this can lead to over a 2x slowdown in compile time.
The good news is that it's fairly easy to fix this. This commit does this using two simple tricks:
1. We now make use of rustc's internal type-query caching by implementing our "does …
> Prevent unnecessary trait resolution

- compiler/rustc_middle/src/ty/sty.rs
- compiler/rustc_mir_transform/src/check_finalizers.rs
- library/std/src/gc.rs
- tests/ui/static/gc/fsa/gc_from.rs
- tests/ui/static/gc/fsa/gc_from.stderr
Previously, when we encountered a GC FSA entry-point (e.g. `Gc::new`) we performed FSA on the argument type of that entry point. When `Gc::new` was our only entry point, this worked fine, because it would always resolve to the `T` in `Gc<T>`.
However, with the addition the of `Gc::from` conversion trait entry point, we can end up being overly conservative with FSA for no good reason. Consider the following:
```rust
let x: Gc<HasRef> = Gc::from(Box::new(HasRef::default()));
```
Where the argument type to this entry-point is `Box<HasRef>`, but the actual constructed `Gc` type is `Gc<HasRef>`. Using our previous approach, we would have to perform FSA on `Box<HasRef>`, even though the `Box` is never used in the context of GC. On large codebases, this lead to FSA rejecting sound `Gc<T>`s.
This …
> Perform FSA on a GC entry point's return type

- compiler/rustc_mir_transform/src/check_finalizers.rs
- tests/ui/static/gc/fsa/auxiliary/types.rs
- tests/ui/static/gc/fsa/basic_calls.rs
- tests/ui/static/gc/fsa/basic_calls.stderr
- tests/ui/static/gc/fsa/drop_glue.rs
- tests/ui/static/gc/fsa/drop_glue.stderr
- tests/ui/static/gc/fsa/monomorphization.rs
- tests/ui/static/gc/fsa/monomorphization.stderr
- tests/ui/static/gc/fsa/recursive_calls.rs
- tests/ui/static/gc/fsa/recursive_calls.stderr
- tests/ui/static/gc/fsa/stdlib_errors.stderr
Previously, if FSA encountered a function (i.e. a drop method, or one
its callsites) which had a type parameter, we would only obtain the
polymorphic MIR for that function. In other words, when FSA checked over
a function, it would check the concrete implementations of that
function. This meant that any uses of type parameters inside that
function would cause an FSA error, because it could never know if it was
safe. For example:
```
fn foo<T>(x: T) {
use(x)
}
```
If `foo` was used inside a drop method, this would always emit an error,
because FSA would not know whether `T: Send + Sync + FinalizerSafe`.
This commit fixes this by attempting to load the monomorphized MIR for a
function if it is available. Where it's not available, we fallback to
checking a function's polymorphic MIR.
> Load monomorphized versions of MIR in FSA 

- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir_transform/src/check_finalizers.rs
- tests/ui/static/gc/fsa/thread_locals.rs
- tests/ui/static/gc/fsa/thread_locals.stderr
Finalizers in Alloy are run on a separate thread, so if a user tries to access a thread-local from within a drop method used as a finalizer it is almost certainly incorrect. This commit disallows this and emit an error when it happens.
> Use FSA to check for thread-locals

- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_mir_transform/src/remove_elidable_drops.rs
- compiler/rustc_session/src/options.rs
- library/std/Cargo.toml
- library/std/src/gc.rs
- library/sysroot/Cargo.toml
- src/bootstrap/src/core/builder.rs
- src/bootstrap/src/core/config/config.rs
- src/bootstrap/src/lib.rs
This adds the following compile-time options to Alloy:
```
finalizer_safety_analysis = true
premature_finalizer_prevention_optimize = true
```
> More compile options

- Cargo.lock
- compiler/rustc/Cargo.toml
- compiler/rustc_middle/Cargo.toml
- compiler/rustc_middle/src/ty/util.rs
- compiler/rustc_mir_transform/Cargo.toml
- compiler/rustc_mir_transform/src/lib.rs
- src/bootstrap/src/core/builder.rs
- src/bootstrap/src/lib.rs
Previously our setup passed a -C rustc option, but this didn't propagate to transitive dependencies so we had instances where programs would be compiled with a mix of different settings.
> Ensure that [alloy] opts in `config.toml` are always applied

- Cargo.lock
- compiler/rustc_mir_transform/Cargo.toml
- compiler/rustc_mir_transform/src/check_finalizers.rs
- tests/ui/runtime/gc/multithreaded.rs
- tests/ui/runtime/gc/thread_local.rs
- tests/ui/runtime/gc/zero_vecs.rs
- tests/ui/static/gc/fsa/stdlib_errors.rs
There are now various combinations of possible checks that FSA can perform which can change dynamically based on previously identified errors (e.g. the discovery of a thread-local means that we no longer check for other things). By passing this around as bit flags it becomes easier to write out the conditional logic.
> Switch to using bitflags for FSA

- compiler/rustc_feature/src/builtin_attrs.rs
- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_span/src/symbol.rs
- library/alloc/src/alloc.rs
- library/alloc/src/boxed.rs
- library/alloc/src/collections/vec_deque/mod.rs
- library/alloc/src/raw_vec.rs
- library/alloc/src/sync.rs
- library/alloc/src/vec/mod.rs
- library/core/src/intrinsics.rs
- library/core/src/panicking.rs
- library/core/src/ub_checks.rs
- library/std/src/io/stdio.rs
Some core library functions (e.g. compiler intrinsics, heap manipulation etc) either use lots of unsafety under the hood or simply do not expose any MIR that FSA can traverse. In this commit we introduce a rustc internal-only attribute (`rustc_fsa_safe_fn`) which allows us to skip over certain functions during FSA and not traverse them. This is never exposed to the user and lets us avoid rewriting Rust library functions with the `FinalizeUnchecked` wrapper.
> Skip certain core library functions during FSA

- compiler/rustc_ty_utils/src/needs_drop.rs
- library/std/src/collections/hash/map.rs
- library/std/src/collections/hash/set.rs
- tests/ui/static/gc/elision/hashmap.rs
- tests/ui/static/gc/elision/hashset.rs
In an ideal world, we would be able to impl `DropMethodFinalizeElidable` on `HashMap` and `HashSet` and get the expected behaviour as we do with `Vec` etc.
However, the backing store for HashMaps and HashSets (hashbrown) is not part of the standard library, and is imported as a separate crate. Rather than maintaining our own fork and trying to keep this in-sync each time we update rustc, it's easier to special case these two types here inside the compiler as they're the only types which need it.
> Finalizer elision: special-case hashmaps and sets

- compiler/rustc_mir_transform/src/check_finalizers.rs
- compiler/rustc_mir_transform/src/remove_elidable_drops.rs
- library/alloc/Cargo.toml
- library/alloc/src/alloc.rs
- library/alloc/src/rc.rs
- library/alloc/src/sync.rs
- library/bdwgc/src/lib.rs
- library/std/Cargo.toml
- library/std/src/gc.rs
- library/std/src/process.rs
- library/std/src/rt.rs
- library/sysroot/Cargo.toml
- src/bootstrap/src/core/config/config.rs
- src/bootstrap/src/lib.rs
This behaviour can be enabled with the `log-stats` build flag.
> Add the ability to log certain GC metrics

- library/std/src/gc.rs
This replaces the call to `GC_keep_alive` inside BDWGC, which uses the same barrier. By inlining, we remove the additional call overhead and isolate the performance implications of premature finalizer prevention to just the barrier. This was noticed when looking at the generated LLVM IR (and ASM): the call to `GC_keep_alive` never appeared to inline across the BDWGC boundary. Of course, this is expected where libgc is a shared object, but it even happens when it's statically linked.
For our premopt experiment, this removes some of the strange results we were seeing where some benchmarks (e.g. SOM quicksort and fibonacci) were ~20% slower on optimized barriers than naive barriers.
> Use inline barriers for premature finalizer prevention

- compiler/rustc/Cargo.toml
- compiler/rustc_mir_transform/Cargo.toml
- compiler/rustc_mir_transform/src/lib.rs
- compiler/rustc_mir_transform/src/log_gc_stats.rs
- src/bootstrap/src/lib.rs
This allows us to get useful information during benchmarking, such as the number of `Gc<T>` pointers in source in the program.
We exclude the standard library from our statistics generation.
> Log compile-time stats about Alloy programs

- compiler/rustc_mir_transform/src/log_gc_stats.rs
- library/std/src/gc.rs
- src/bootstrap/src/lib.rs
Previously the stat counts for the alloc crate were recorded incorrectly because as any heap allocation recorded before the first `GC:new` was being overwritten. This resulted in us incorrectly recording the ratio of GC to non-GC heap objects and over-representing how many objects were under control of GC.
> Fix GC metric collection

- library/alloc/src/alloc.rs
- library/bdwgc/src/lib.rs
- library/std/src/gc.rs
With this API, Boehm automatically invokes our finalization-thread code when there is finalization work to do (using GC_set_finalizer_notifier) and handles synchronization internally.
> Use BDWGC finalization callback API

- library/std/src/gc.rs
This commit first fixes an issue where Alloy did not record  when a finalizer thread had already been spawned. This alone removes the finalizer count anomalies and brings performance back up to ~20% slower than our previous finalization model [1].
Second, by introducing a condition variable to sleep the finalizer thread when there is no work to do we now see that our elision benchmark results are statistically indistinguishable to [1].
[1]: Benchmarks run using Alloy from commit #abe23a2c
> Use a cond var to sleep finalizer thread

- library/bdwgc/src/lib.rs
- library/std/src/gc.rs
- tests/ui/runtime/gc/disable.rs
This is useful for debugging and, for us in particular, benchmarking. Before this, we had to make sure that we passed GC_DONT_GC=true|false to the correct benchmark configuration which was hacky and errorprone. Now we can ensure that GC is enabled or disabled as part of the benchmark patch file.
> Add API for enabling/disabling collector

- library/alloc/src/boxed.rs
- library/alloc/src/rc.rs
- tests/ui/box/issue-95036.rs
- tests/ui/box/large-allocator-ice.rs
- tests/ui/debuginfo/debuginfo-box-with-large-allocator.rs
- tests/ui/lint/must_not_suspend/allocator.rs
- tests/ui/lint/must_not_suspend/allocator.stderr
- tests/ui/lto/issue-100772.rs
Uses the same rustc_lint as #3410301
> Prevent unsound Box allocations
